base_dir: "/mimer/NOBACKUP/groups/naiss2025-6-138/HCLIMAI/Emilia_Romagna"
#GCM: "ICHEC-EC-EARTH_HIST"
#FIRST_YEAR: "1995"
#LAST_YEAR: "2005"
GCM: "ECMWF-ERAINT"
FIRST_YEAR_12km: "2000"
LAST_YEAR_12km: "2009"
FIRST_YEAR_3km: "2000"
LAST_YEAR_3km: "2009"

variables: 
  - "tas"
#"tas" "hfls" "mrsol"

experiment: "SRGAN_CNN_ERAI_TOROG"
MLEXP: ''

data_path:
  HCLIM 3km tas: "${base_dir}/cropped/${GCM}/3km/6hr/tas/tas_3km_6hr_${FIRST_YEAR_3km}01010000-${LAST_YEAR_3km}12311800.nc"
  HCLIM 12km tas: "${base_dir}/cropped/${GCM}/12km/6hr/tas/tas_12km_6hr_${FIRST_YEAR_12km}01010000-${LAST_YEAR_12km}12311800.nc"
  SRGANWORO 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_worog_bs60_ERAI_alvis/predictant_ypred_1.nc"
  SRGANNORO 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_norog_bs60_ERAI_alvis/predictant_ypred_1.nc"
  #CNN 3km tas: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_tas_2009.nc"

time_range:
  HCLIM 12km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  HCLIM 3km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
             'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANWORO 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANNORO 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  CNN 3km: {'mrsol': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'tas': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  target: {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}

output_dir: "${base_dir}/statistic_figs/1var/tas_test" 

statistics:
  - rmse
  #- correlation
  - mean_bias
  - variance_ratio
  #- wasserstein
  - percentile_99
  - mean_value
  - abs_value
  #- std

min_max_scale:
  'rmse': 
  #'correlation': [0.88, 1.00]
  'mean_bias':
  'variance_ratio':
  #'wasserstein':
  'percentile_99': 
  'mean_value':
  'abs_value':
  #'std':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

fig_parameters:
  'nrows_def': 5
  'ncols_def': 5
  'figsize_def': [30,20]
  'fontsize_def': 18
  'nlevels_def': 11
  'extend_def': 'neither'
