base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna"
#GCM: "ICHEC-EC-EARTH_HIST"
#FIRST_YEAR: "1995"
#LAST_YEAR: "2005"

GCM: "ECMWF-ERAINT"
FIRST_YEAR_12km: "2000"
LAST_YEAR_12km: "2009"
FIRST_YEAR_3km: "2000"
LAST_YEAR_3km: "2009"

variables: 
  - "mrsol"
  - "tas"
#"tas" "hfls" "mrsol"

experiment: "SRGAN_CNN_bs50_lamb0.1_wtm_ERAI"

data_path:
  #tas
  #HCLIM 3km: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}_no_pr/predictant_ytest.nc"
  #HCLIM 12km: "${base_dir}/SG/SRGAN_OUT/EPOCH1_${variables}_with_${variables}/predictor.nc"
  HCLIM 3km mrsol: "${base_dir}/cropped/${GCM}/3km/6hr/mrsol/mrsol_3km_6hr_${FIRST_YEAR_3km}01010000-${LAST_YEAR_3km}12311800.nc"
  HCLIM 3km tas: "${base_dir}/cropped/${GCM}/3km/6hr/tas/tas_3km_6hr_${FIRST_YEAR_3km}01010000-${LAST_YEAR_3km}12311800.nc"
  HCLIM 12km mrsol: "${base_dir}/cropped/${GCM}/12km/6hr/mrsol/mrsol_12km_6hr_${FIRST_YEAR_12km}01010000-${LAST_YEAR_12km}12311800.nc"
  HCLIM 12km tas: "${base_dir}/cropped/${GCM}/12km/6hr/tas/tas_12km_6hr_${FIRST_YEAR_12km}01010000-${LAST_YEAR_12km}12311800.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_mrsol_with_mrsol_val0.1_atos/predictant_ypred.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_with_tas_val0.1_atos/predictant_ypred.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_mrsol_scale_space_val0.1_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_space_val0.1_atos/predictant_ypred_1.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_val0.1_atos/predictant_ypred.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_val0.1_atos/predictant_ypred.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_global_val0.1_batch20_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_global_val0.1_batch20_atos/predictant_ypred_1.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_global_corrlambda0.5_val0.1_batch20_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_global_corrlambda0.5_val0.1_batch20_atos/predictant_ypred_1.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_dr0.2_val0.1_batch20_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_dr0.2_val0.1_batch20_atos/predictant_ypred_1.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_batch50_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_batch50_atos/predictant_ypred_1.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_dr0.2_batch50_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_dr0.2_batch50_atos/predictant_ypred_1.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_dr0.2_dlr1e-5_batch50_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_dr0.2_dlr1e-5_batch50_atos/predictant_ypred_1.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_dlr1e-5_batch50_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_dlr1e-5_batch50_atos/predictant_ypred_1.nc"

  SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_batch50_lamb0.1_wtm_atos/predictant_ypred_1.nc"
  SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_scale_time_val0.1_batch50_lamb0.1_wtm_atos/predictant_ypred_1.nc"

  #SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_with_sm_ERAI_corrlamda0_val0.1_atos/predictant_ypred_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_with_sm_ERAI_corrlamda0_val0.1_atos/predictant_ypred_1.nc"

  #SRGAN 3km tas mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_val0.1_atos/predictant_ypred.nc"
  #SRGAN 3km tas mrsol b20: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_val0.1_batch20_atos/predictant_ypred.nc"
  #SRGAN 3km tas mrsol with tm b20: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_with_tm_val0.1_batch20_atos/predictant_ypred.nc"
  CNN 3km mrsol: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_mrsol_2009.nc"
  CNN 3km tas: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_tas_2009.nc"

time_range:
  HCLIM 12km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  HCLIM 3km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
             'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  CNN 3km: {'mrsol': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'tas': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  target: {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}

output_dir: "${base_dir}/statistic_figs" 

statistics:
  #- rmse
  - cpl_corr
  #- correlation
  #- mean_bias
  #- variance_ratio
  #- wasserstein
  #- percentile_99
  #- mean_value
  #- abs_value
  #- std

min_max_scale:
  #'rmse': 
  ##'correlation': [0.88, 1.00]
  'cpl_corr': [-1.0, 1.0]
  #'correlation':
  #'mean_bias':
  #'variance_ratio':
  #'wasserstein':
  #'percentile_99': 
  #'mean_value':
  #'abs_value':
  #'std':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

fig_parameters:
  'nrows_def': 2
  'ncols_def': 2
  'figsize_def': [30,20]
  'nlevels_def': 11
