base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Test_Domain"

GCM: "ECMWF-ERAINT"
FIRST_YEAR_12km: "2000"
LAST_YEAR_12km: "2009"
FIRST_YEAR_3km: "2000"
LAST_YEAR_3km: "2009"

variables: 
  - "mrsol"
  - "tas"

experiment: "SRGAN_ERAI"

data_path:
  #HCLIM 3km: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_no_pr/predictant_ytest.nc"
  #HCLIM 12km: "${base_dir}/SG/SRGAN_OUT/EPOCH1_tas_with_tas/predictor.nc"
  #SRGAN 3km: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_no_pr/predictant_ypred.nc"

  HCLIM 3km mrsol: "${base_dir}/${GCM}/3km/6hr/mrsol/mrsol_3km_6hr_${FIRST_YEAR_3km}01010000-${LAST_YEAR_3km}12311800.nc"
  HCLIM 3km tas: "${base_dir}/${GCM}/3km/6hr/tas/tas_3km_6hr_${FIRST_YEAR_3km}01010000-${LAST_YEAR_3km}12311800.nc"
  HCLIM 12km mrsol: "${base_dir}/${GCM}/12km/6hr/mrsol/mrsol_12km_6hr_${FIRST_YEAR_12km}01010000-${LAST_YEAR_12km}12311800.nc"
  HCLIM 12km tas: "${base_dir}/${GCM}/12km/6hr/tas/tas_12km_6hr_${FIRST_YEAR_12km}01010000-${LAST_YEAR_12km}12311800.nc"

  SRGAN 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_atos/predictant_ypred_1.nc"
  SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_atos/predictant_ypred_1.nc"

  SRGANDR01 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_dr0.1_atos/predictant_ypred_1.nc"
  SRGANDR01 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_dr0.1_atos/predictant_ypred_1.nc"

  SRGANDR02 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_dr0.2_atos/predictant_ypred_1.nc"
  SRGANDR02 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_dr0.2_atos/predictant_ypred_1.nc"

  SRGANDR03 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_dr0.3_atos/predictant_ypred_1.nc"
  SRGANDR03 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_dr0.3_atos/predictant_ypred_1.nc"

  SRGANBS100 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_bs100_atos/predictant_ypred_1.nc"
  SRGANBS100 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_bs100_atos/predictant_ypred_1.nc"

  SRGANBS100DR02 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_bs100_dr0.2_atos/predictant_ypred_1.nc"
  SRGANBS100DR02 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_bs100_dr0.2_atos/predictant_ypred_1.nc"

  SRGANBS100DR02DLR1E-5 3km mrsol: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_bs100_dr0.2_dlr1e-5_atos/predictant_ypred_1.nc"
  SRGANBS100DR02DLR1E-5 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_mrsol_bs100_dr0.2_dlr1e-5_atos/predictant_ypred_1.nc"

  #CNN 3km: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_${variables}_2009.nc"

time_range:
  HCLIM 12km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  HCLIM 3km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
             'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANDR01 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANDR02 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANDR03 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANBS100 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANBS100DR02 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANBS100DR02DLR1E-5 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  target: {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}

output_dir: "${base_dir}/statistic_figs" 

statistics:
  #- rmse
  - cpl_corr
  #- correlation
  #- mean_bias
  #- variance_ratio
  #- wasserstein
  #- percentile_99
  #- mean_value
  #- abs_value
  #- std

min_max_scale:
  #'rmse': 
  ##'correlation': [0.88, 1.00]
  'cpl_corr':
  #'correlation':
  #'mean_bias':
  #'variance_ratio':
  #'wasserstein':
  #'percentile_99': 
  #'mean_value':
  #'abs_value':
  #'std':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

fig_parameters:
  'nrows_def': 3
  'ncols_def': 3
  'figsize_def': [20,20]
  'nlevels_def': 11
