base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Test_Domain"
GCM: "ECMWF-ERAINT"
FIRST_YEAR_12km: "2000"
LAST_YEAR_12km: "2009"
FIRST_YEAR_3km: "2000"
LAST_YEAR_3km: "2009"

variables: 
  - "pr"
#"tas" "hfls" "mrsol"

experiment: "SRGAN_pr"

data_path:
  HCLIM 3km pr: "${base_dir}/${GCM}/3km/6hr/pr/pr_3km_6hr_200001010300-200912312100.nc"
  HCLIM 12km pr: "${base_dir}/${GCM}/12km/6hr/pr/pr_12km_6hr_200001010300-200912312100.nc"
  SRGANATOS 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_atos/predictant_ypred.nc"
  SRGAN2CHATOS 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_pr_atos/predictant_ypred.nc"
  SRGANWPFREJA 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_with_pr/predictant_ypred.nc"
  SRGANNPFREJA 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_pr_no_pr/predictant_ypred.nc"
  SRGANGPU 3km pr: "${base_dir}/SG/SRGAN_OUT/EPOCH50_pr_scale_time_stdscaler_gpufix_bs100_ERAI_atos/predictant_ypred_1.nc"

  #SRGAN 3km def: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}_no_pr/predictant_ypred.nc"
  #SRGAN 3km droplr: "${base_dir}/SG/SRGAN_OUT/EPOCH100_${variables}_dropout0.3_lr1e-5_discdrop_genalldrop/predictant_ypred.nc"
  #CNN 3km: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_${variables}_2009.nc"

time_range:
  HCLIM 12km: {'pr': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  HCLIM 3km:  {'pr': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANATOS 3km:  {'pr': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANWPFREJA 3km: { 'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANNPFREJA 3km: { 'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN2CHATOS 3km: { 'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANGPU 3km: { 'pr':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  CNN 3km: {'pr': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  target: {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}

output_dir: "${base_dir}/statistic_figs/1var" 

statistics:
  - rmse
  - correlation
  - mean_bias
  - variance_ratio
  - wasserstein
  - percentile_99
  - mean_value
  - abs_value
  #- std

min_max_scale:
  'rmse': 
  'correlation': [0.88, 1.00]
  'mean_bias':
  'variance_ratio':
  'wasserstein':
  'percentile_99': 
  'mean_value':
  'abs_value':
  #'std':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

fig_parameters:
  'nrows_def': 5
  'ncols_def': 5
  'figsize_def': [35,20]
  'nlevels_def': 11
