base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Test_Domain"
GCM: "ECMWF-ERAINT"
FIRST_YEAR_12km: "2000"
LAST_YEAR_12km: "2009"
FIRST_YEAR_3km: "2000"
LAST_YEAR_3km: "2009"

variables: 
  - "tas"
#"tas" "hfls" "mrsol"

experiment: "SRGAN_tas"

data_path:
  #HCLIM 3km: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_no_pr/predictant_ytest.nc"
  #HCLIM 12km: "${base_dir}/SG/SRGAN_OUT/EPOCH1_tas_with_tas/predictor.nc"
  HCLIM 3km tas: "${base_dir}/${GCM}/3km/6hr/tas/tas_3km_6hr_${FIRST_YEAR_3km}01010000-${LAST_YEAR_3km}12311800.nc"
  HCLIM 12km tas: "${base_dir}/${GCM}/12km/6hr/tas/tas_12km_6hr_${FIRST_YEAR_12km}01010000-${LAST_YEAR_12km}12311800.nc"

  SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_no_pr/predictant_ypred.nc"
  SRGANLR1E-5 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_lr1e-5/predictant_ypred.nc"
  SRGANDR0.3 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_drop0.3/predictant_ypred.nc"

  #SRGANVAL01 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_val0.1/predictant_ypred.nc"
  #SRGAN 3km LUMI val0.2: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_val0.2/predictant_ypred.nc"
  #SRGAN 3km LUMI val0.2_earlystop: "${base_dir}/SG/SRGAN_OUT/EPOCH200_tas_val0.2_earlystop/predictant_ypred.nc"
  #SRGANLUMIVAL01DAUG 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_val0.2_daug/predictant_ypred.nc"
  #SRGANLUMIVAL02DAUG03 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_val0.2_daug0.3/predictant_ypred.nc"
  #SRGANLUMIVAL02DR3 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_val0.2_drop3/predictant_ypred.nc"
  #SRGANLUMIVAL02E200 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH200_tas_val0.2/predictant_ypred.nc"

  SRGANDR03 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_atos_drop0.3/predictant_ypred.nc"
  SRGANDR05 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_atos_drop0.5/predictant_ypred.nc"
  SRGANGLR1E-5DLR2E-4 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_atos_glr1e-4_dlr2e-4/predictant_ypred.nc"
  SRGANGLR2E-4DLR1E-3 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_atos_glr2e-4_dlr1e-3/predictant_ypred.nc"
  #SRGAN2CHANNELS 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_pr_atos/predictant_ypred.nc"
  SRGANDR0.3LR1E-5 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_dropout0.3_lr1e-5_discdrop_genalldrop/predictant_ypred.nc"
  SRGANBS100 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_bs100_atos/predictant_ypred_1.nc"
  SRGANBS100LAM01 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_bs100_lamb0.1_atos/predictant_ypred_1.nc"
  SRGANSCSTDBS100 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_bs100_ERAI_atos/predictant_ypred_1.nc"
  SRGANSCRBSBS100 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_rbsscaler_bs100_ERAI_atos/predictant_ypred_1.nc"
  SRGANSCSTDGPUBS100 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH50_tas_scale_time_stdscaler_gpufix_bs100_ERAI_atos/predictant_ypred_1.nc"

  #CNN 3km: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_${variables}_2009.nc"

time_range:
  HCLIM 12km: {'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  HCLIM 3km:  {'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN 3km:  {'tas': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANLR1E-5 3km: { 'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANDR0.3 3km: { 'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANDR03 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANDR05 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANGLR1E-5DLR2E-4 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANGLR2E-4DLR1E-3 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANDR0.3LR1E-5 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANBS100 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANBS100LAM01 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANSCSTDBS100 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANSCRBSBS100 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANSCSTDGPUBS100 3km: {'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  CNN 3km: {'tas': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  target: {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}

output_dir: "${base_dir}/statistic_figs/1var" 

statistics:
  - rmse
  - correlation
  - mean_bias
  - variance_ratio
  - wasserstein
  - percentile_99
  - mean_value
  - abs_value
  #- std

min_max_scale:
  'rmse': 
  'correlation': [0.88, 1.00]
  'mean_bias':
  'variance_ratio':
  'wasserstein':
  'percentile_99': 
  'mean_value':
  'abs_value':
  #'std':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

fig_parameters:
  'nrows_def': 5
  'ncols_def': 5
  'figsize_def': [35,20]
  'nlevels_def': 11
