base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna"

variables: 
  - "tas"
#"tas" "hfls" "mrsol"

experiment: "SRGAN_ECEHisFutMC_withtas_2005"

data_path:
  #ECE, Hist, 1996-2005
  #HCLIM 3km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_HIST/3km/6hr/tas/tas_3km_6hr_199501010000-200512311800.nc"
  #HCLIM 12km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_HIST/12km/6hr/tas/tas_12km_6hr_199501010000-200512311800.nc"
  #SRGAN HCLIM 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHistFut_atos/predictant_ytest_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHistFut_atos/predictant_ypred_1.nc"
  #ECE, MC, 2046-2050
  #HCLIM 3km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_RCP85_MC/3km/6hr/tas/tas_3km_6hr_204001010000-205012311800.nc"
  #HCLIM 12km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_RCP85_MC/12km/6hr/tas/tas_12km_6hr_204001010000-205012311800.nc"
  #SRGAN HCLIM 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHistFut_atos/predictant_ytest_2.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHistFut_atos/predictant_ypred_2.nc"
  #ECE, Hist, 1996-2005, with tas
  HCLIM 3km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_HIST/3km/6hr/tas/tas_3km_6hr_199501010000-200512311800.nc"
  HCLIM 12km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_HIST/12km/6hr/tas/tas_12km_6hr_199501010000-200512311800.nc"
  SRGAN HCLIM 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHistFutMC_withtas_atos/predictant_ytest_1.nc"
  SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHistFutMC_withtas_atos/predictant_ypred_1.nc"
  #ECE, MC, 2046-2050, with tas
  #HCLIM 3km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_RCP85_MC/3km/6hr/tas/tas_3km_6hr_204001010000-205012311800.nc"
  #HCLIM 12km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_RCP85_MC/12km/6hr/tas/tas_12km_6hr_204001010000-205012311800.nc"
  #SRGAN HCLIM 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHistFutMC_withtas_atos/predictant_ytest_2.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHistFutMC_withtas_atos/predictant_ypred_2.nc"


  #ECE, Hist 1996-2005
  #HCLIM 3km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_HIST/3km/6hr/tas/tas_3km_6hr_199501010000-200512311800.nc"
  #HCLIM 12km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_HIST/12km/6hr/tas/tas_12km_6hr_199501010000-200512311800.nc"
  #SRGAN HCLIM 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHis_atos/predictant_ytest_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHis_atos/predictant_ypred_1.nc"
  #ECE, Hist 1996-2005, with tas
  #HCLIM 3km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_HIST/3km/6hr/tas/tas_3km_6hr_199501010000-200512311800.nc"
  #HCLIM 12km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_HIST/12km/6hr/tas/tas_12km_6hr_199501010000-200512311800.nc"
  #SRGAN HCLIM 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHis_withtas_atos/predictant_ytest_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEHis_withtas_atos/predictant_ypred_1.nc"

  #ECE, MC 2041-2050
  #HCLIM 3km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_RCP85_MC/3km/6hr/tas/tas_3km_6hr_204001010000-205012311800.nc"
  #HCLIM 12km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_RCP85_MC/12km/6hr/tas/tas_12km_6hr_204001010000-205012311800.nc"
  #SRGAN HCLIM 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEFutMC_atos/predictant_ytest_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEFutMC_atos/predictant_ypred_1.nc"
  #ECE, MC 2041-2050, with tas
  #HCLIM 3km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_RCP85_MC/3km/6hr/tas/tas_3km_6hr_204001010000-205012311800.nc"
  #HCLIM 12km tas: "${base_dir}/cropped/ICHEC-EC-EARTH_RCP85_MC/12km/6hr/tas/tas_12km_6hr_204001010000-205012311800.nc"
  #SRGAN HCLIM 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEFutMC_withtas_atos/predictant_ytest_1.nc"
  #SRGAN 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_ECEFutMC_withtas_atos/predictant_ypred_1.nc"

output_dir: "${base_dir}/statistic_figs" 

statistics:
  #- rmse
  ##- cpl_corr
  #- correlation
  #- mean_bias
  #- variance_ratio
  #- wasserstein
  #- percentile_99
  #- mean_value
  #- abs_value
  - std

min_max_scale:
  #'rmse': 
  ##'correlation': [0.88, 1.00]
  ##'cpl_corr':
  #'correlation':
  #'mean_bias':
  #'variance_ratio':
  #'wasserstein':
  #'percentile_99': 
  #'mean_value':
  #'abs_value':
  'std':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

