base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna"
#GCM: "ICHEC-EC-EARTH_HIST"
#FIRST_YEAR: "1995"
#LAST_YEAR: "2005"
GCM: "ECMWF-ERAINT"
FIRST_YEAR_12km: "2000"
LAST_YEAR_12km: "2009"
FIRST_YEAR_3km: "2000"
LAST_YEAR_3km: "2009"

variables: 
  - "tas"
#"tas" "hfls" "mrsol"

experiment: "SRGAN_NTNOROGSENS_CNN_ERAI_SCSTD_GPU_paper"
#experiment: "SRGAN_WTWOROG_CNN_ERAI_SCSTD_GPU_paper"
MLEXP: ''

data_path:
  HCLIM 3km tas: "${base_dir}/cropped/${GCM}/3km/6hr/tas/tas_3km_6hr_${FIRST_YEAR_3km}01010000-${LAST_YEAR_3km}12311800.nc"
  #HCLIM 12km tas: "${base_dir}/cropped/${GCM}/12km/6hr/tas/tas_12km_6hr_${FIRST_YEAR_12km}01010000-${LAST_YEAR_12km}12311800.nc"
  # Fig 3 & 4, with tas with orog as input
  #SRGAN 3km tas:  "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_wt_worog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"
  # Fig on sensitivity test on tas and orog as input
  SRGAN_NTNOROG 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_norog_gpufix_lnoise0.1_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
  SRGAN_NTWOROG 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_gpufix_lnoise0.1_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
  #SRGAN_NTWOROG 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
  SRGAN_WTNOROG 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_wt_norog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"
  #SRGAN_WTNOROGv2 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_wt_norog_gpufix_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
  #SRGAN_WTWOROG 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_wt_worog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"
  #CNN 3km tas: "/nobackup/rossby27/users/sm_yicwa/DATA_shared/Climulator/Emulator_HCLIM_CRM_T_SM/cnn_prediction_tas_2009.nc"

  # not used
  #SRGAN_WSMNTNOROG 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_wsm_nt_norog_gpufix_bs50_ERAI_atos/predictant_ypred_1.nc"
  #SRGAN_WSMNTNOROGv2 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_scale_time_stdscaler_wsm_nt_norog_gpufix_bs50_ERAI_atos_v2/predictant_ypred_1.nc"
time_range:
  HCLIM 12km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  HCLIM 3km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
             'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN_NTNOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN_NTWOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN_WTWOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN_WTNOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN_WTNOROGv2 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN_WSMNTNOROG 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGAN_WSMNTNOROGv2 3km: {'mrsol':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  CNN 3km: {'mrsol': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
           'tas': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  target: {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}

output_dir: "${base_dir}/statistic_figs/1var/paper" 
#output_dir: "/nobackup/rossby27/users/sm_yicwa/PROJECTS/01-PROJ_emulator/04-evaluation_fuxing/statistic_figs"

statistics:
  - rmse
  #- correlation
  - mean_bias
  - variance_ratio
  #- wasserstein
  - percentile_99
  - mean_value
  - abs_value
  #- std

min_max_scale:
  'rmse': 
  #'correlation': [0.88, 1.00]
  'mean_bias':
  'variance_ratio':
  #'wasserstein':
  'percentile_99': 
  'mean_value':
  'abs_value':
  #'std':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

fig_parameters:
  'nrows_def': 2
  'ncols_def': 2
  'figsize_def': [22,15]
  #'nrows_def': 2
  #'ncols_def': 3
  #'figsize_def': [20,10]
  'fontsize_def': 24
  'nlevels_def': 11
  'extend_def': 'neither'
