base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna"
#GCM: "ICHEC-EC-EARTH_HIST"
#FIRST_YEAR: "1995"
#LAST_YEAR: "2005"
GCM: "ECMWF-ERAINT"
FIRST_YEAR_12km: "2000"
LAST_YEAR_12km: "2009"
FIRST_YEAR_3km: "2000"
LAST_YEAR_3km: "2009"

variables: 
  - "tas"
#"tas" "hfls" "mrsol"

experiment: "SRGAN_ERAI_2003"

data_path:
  HCLIM 3km tas: "${base_dir}/cropped/${GCM}/3km/6hr/tas/tas_3km_6hr_${FIRST_YEAR_3km}01010000-${LAST_YEAR_3km}12311800.nc"
  HCLIM 12km tas: "${base_dir}/cropped/${GCM}/12km/6hr/tas/tas_12km_6hr_${FIRST_YEAR_12km}01010000-${LAST_YEAR_12km}12311800.nc"
  SRGANSCSTDBS50GPUNSTD0.03 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_wsm_scale_time_stdscaler_gpufix_nstd0.03_bs50_2003_ERAI_atos/predictant_ypred_1.nc"
  SRGANSCSTDBS50GPULNOISE0.1 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_wsm_scale_time_stdscaler_gpufix_lnoise0.1_bs50_2003_ERAI_atos/predictant_ypred_1.nc"
  SRGANSCMNXBS50GPU 3km tas: "${base_dir}/SG/SRGAN_OUT/EPOCH100_tas_wsm_scale_time_mnxscaler_gpufix_bs50_2003_ERAI_atos/predictant_ypred_1.nc"


time_range:
  HCLIM 12km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
              'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  HCLIM 3km: {'mrsol': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, 
             'tas': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"], 'step_hours': 6}, }
  SRGANSCSTDBS50GPUNSTD0.03 3km: {'mrsol':{'start_date': ["2003-01-01 00:00"], 'end_date': ["2003-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2003-01-01 00:00"], 'end_date': ["2003-12-31 24:00"], 'step_hours': 6}, }
  SRGANSCSTDBS50GPULNOISE0.1 3km: {'mrsol':{'start_date': ["2003-01-01 00:00"], 'end_date': ["2003-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2003-01-01 00:00"], 'end_date': ["2003-12-31 24:00"], 'step_hours': 6}, }
  SRGANSCMNXBS50GPU 3km: {'mrsol':{'start_date': ["2003-01-01 00:00"], 'end_date': ["2003-12-31 24:00"], 'step_hours': 6, }, 
              'tas':{'start_date': ["2003-01-01 00:00"], 'end_date': ["2003-12-31 24:00"], 'step_hours': 6}, }
  target: {'start_date': ["2003-01-01 00:00"], 'end_date': ["2003-12-31 24:00"], 'step_hours': 6}

output_dir: "${base_dir}/statistic_figs/1var" 
#output_dir: "/nobackup/rossby27/users/sm_yicwa/PROJECTS/01-PROJ_emulator/04-evaluation_fuxing/statistic_figs"

statistics:
  - rmse
  - correlation
  - mean_bias
  - variance_ratio
  - wasserstein
  - percentile_99
  - mean_value
  - abs_value
  #- std

min_max_scale:
  'rmse': 
  'correlation': [0.88, 1.00]
  'mean_bias':
  'variance_ratio':
  'wasserstein':
  'percentile_99': 
  'mean_value':
  'abs_value':
  #'std':

abs_value_max_scale:
  'pr': 0.5
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

unit_convert:
  'pr': 86400.0
  'tas': 1.0
  'mrsol': 1.0
  'hfls': 1.0

fig_parameters:
  'nrows_def': 5
  'ncols_def': 4
  'figsize_def': [30,20]
  'nlevels_def': 11
